magazen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.welcome, name='welcome'),

    path('detail/<int:magazen_id>/', views.detail_view, name='detail'),
    path('about/', views.about, name='about'),

    path('jurnal/', views.jurnals_view, name='jurnals'),
    path('jurnal/<int:jurnal_id>/', views.jurnal_view, name='jurnal'),

    path('gazeta/', views.gazetas_view, name='gazetas'),
    path('gazeta/<int:gazeta_id>/', views.gazeta_view, name='gazeta'),

    path('maqola/', views.maqolas_view, name='maqolas'),
    path('maqola/<int:maqola_id>/', views.maqola_view, name='maqola'),
]

main/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

import os
from datetime import datetime


def upload_to(instance, filename):
    # Get current date
    now = datetime.now()
    # Define the upload path
    year_month = now.strftime('%Y-%m')  # Format: YYYY-MM

    # Modify filename (example: adding timestamp)
    filename_without_ext, ext = os.path.splitext(filename)
    timestamp = now.strftime('%Y%m%d%H%M%S')
    new_filename = f"{timestamp}{ext}"

    return os.path.join('uploads', year_month, new_filename)


class Category(models.Model):
    name = models.CharField(verbose_name='category', max_length=50)

    def __str__(self):
        return self.name


class Magazen(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to=upload_to, default="/media/image/logotip.ico", null=True, blank=True)
    file = models.FileField(upload_to=upload_to)
    content = RichTextUploadingField(verbose_name="Content")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Announcement(models.Model):
    name = models.CharField(max_length=255, verbose_name="name")
    author = models.CharField(max_length=255, verbose_name="author")
    image = models.ImageField(upload_to='image/', default='image/image.jpg')
    content = RichTextUploadingField(verbose_name="Content")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from .models import Magazen


def welcome(request):
    context = {
        'magazens': Magazen.objects.all()
    }
    return render(request, 'main/welcome.html', context)


def magazens_view(request):
    magazens = Magazen.objects.all()
    return render(request, 'main/magazens.html', {'magazens': magazens})


def detail_view(request, magazen_id):
    magazen = Magazen.objects.get(id=magazen_id)
    return render(request, 'main/detail.html', {'magazen': magazen})


def about(request):
    return render(request, 'main/about.html')


def jurnals_view(request):
    return None


def jurnal_view(request):
    return None


def gazetas_view(request):
    return None


def gazeta_view(request):
    return None


def maqolas_view(request):
    return None


def maqola_view(request):
    return None

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <title>JobEntry - Job Portal Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap"
          rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<div class="container-xxl bg-white p-0">
    <!-- Spinner Start -->
    <div id="spinner"
         class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a href="{% url 'main:welcome' %}" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
            <h1 class="m-0 text-primary">Mutafakkir</h1>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="#" class="nav-item nav-link">Tahrir hay'ati</a>
                <a href="#" class="nav-item nav-link">Kuzatuv kengashi</a>
                <a href="#" class="nav-item nav-link">E'lon</a>
            </div>
            <a href="#" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">
                Jurnallar
                <i class="fa fa-arrow-right ms-3"></i>
            </a>
        </div>
    </nav>
    <!-- Navbar End -->
{% block content %}
	
{% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">
                        Mutafakkir
                    </h5>
                    <a class="btn btn-link text-white-50" href="">Asosiy</a>
                    <a class="btn btn-link text-white-50" href="">Gazetalar</a>
                    <a class="btn btn-link text-white-50" href="">Nimadirlar</a>
                    <a class="btn btn-link text-white-50" href="">Biz haqimizda</a>
                </div>
                
                <div class="col-lg-6 col-md-6">
                    <h5 class="text-white mb-4">Biz bilan aloqa</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>103, Taraqqiyot ko'chasi Toshkent shaxar</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+998 88 959 91 89</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>mutaffakir@gmail.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Newsletter</h5>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <label>
                            <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text"
                                   placeholder="Your email">
                        </label>
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">
                            SignUp
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="https://mutafakkir.uz/">
                        Mutafakkir
                    </a>
                        , Barcha huquqlar himoyalangan. 
                        <a class="border-bottom" href="https://github.com/TalantDeveloper">
                            TalantDeveloper
                        </a>
                        tomonidan ishlab chiqilgan
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- About Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5 align-items-center">
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                    <div class="row g-0 about-bg rounded overflow-hidden">
                        <div class="col-6 text-start">
                            <img class="img-fluid w-100" src="{% static 'img/about-1.jpg' %}" alt="">
                        </div>
                        <div class="col-6 text-start">
                            <img class="img-fluid" src="{% static 'img/about-2.jpg' %}"
                                 style="width: 85%; margin-top: 15%;" alt="">
                        </div>
                        <div class="col-6 text-end">
                            <img class="img-fluid" src="{% static 'img/about-3.jpg' %}" style="width: 85%;" alt="">
                        </div>
                        <div class="col-6 text-end">
                            <img class="img-fluid w-100" src="{% static 'img/about-4.jpg' %}" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                    <h1 class="mb-4">We Help To Get The Best Job And Find A Talent</h1>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et
                        eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat
                        amet</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Tempor erat elitr rebum at clita</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Aliqu diam amet diam et eos</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Clita duo justo magna dolore erat amet</p>
                    <a class="btn btn-primary py-3 px-5 mt-3" href="">Read More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
{% endblock %}

templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Job Detail Start -->
    <div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row gy-5 gx-4">
                <div class="col-lg-8">
                    <div class="d-flex align-items-center mb-5">
                        <img class="flex-shrink-0 img-fluid border rounded" src="{{ magazen.image.url }}"
                             alt=""
                             style="width: 80px; height: 80px;">
                        <div class="text-start ps-4">
                            <h3 class="mb-3">{{ magazen.name }}</h3>
                            <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>
                                Toshkent, O'zbekiston
                            </span>
                            <span class="text-truncate me-3">
                                <i class="far fa-clock text-primary me-2"></i>
                                Gazeta
                            </span>
                        </div>
                    </div>

                    <div class="mb-5">
                        <h4 class="mb-3">Gazeta haqida</h4>
                            {{ magazen.content| safe }}
                    </div>
                    <div class="">
                        <div class="col-12">
                            <button class="btn btn-primary w-100" type="submit">Gazetani ko'rish</button>
                        </div>

                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="bg-light rounded p-5 mb-4 wow slideInUp" data-wow-delay="0.1s">
                        <h4 class="mb-4">
                            Gazeta haqida
                        </h4>
                        <p><i class="fa fa-angle-right text-primary me-2"></i>Sana: 21.06.2024 </p>
                        <p><i class="fa fa-angle-right text-primary me-2"></i>Turi: Gazeta</p>
                        <p><i class="fa fa-angle-right text-primary me-2"></i>Joylashuv: Toshkent, O'zbekiston</p>
                    </div>
                    <div class="bg-light rounded p-5 wow slideInUp" data-wow-delay="0.1s">
                        <h4 class="mb-4">
                            Muallif haqida
                        </h4>
                        <p class="m-0">
                            Jamiyat rivoji uchun qiziqarli va foydali ma'lumotlarni yoritish.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Job Detail End -->
{% endblock %}